<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Description>Provides a handful amount of options to manipulate editor level files.</Description>
    <FileVersion>2.0.3.2</FileVersion>
    <AssemblyVersion>2.0.3.2</AssemblyVersion>
    <PackageIcon></PackageIcon>
    <ApplicationIcon>cbldtobld.ico</ApplicationIcon>
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="cbldtobld.ico" />
  </ItemGroup>

  <ItemGroup>
	 
	 <Reference Include="0Harmony">
	   <HintPath>..\..\..\..\..\Steam\steamapps\common\Baldi's Basics Plus\BepInEx\core\0Harmony.dll</HintPath>
	 </Reference>
	 
	 <Reference Include="Assembly-CSharp">
	   <HintPath>..\..\..\..\..\Steam\steamapps\common\Baldi's Basics Plus\BALDI_Data\Managed\Assembly-CSharp.dll</HintPath>
	 </Reference>
	 
	 <Reference Include="BaldiLevelEditor">
	 <HintPath>References\BaldiLevelEditor.dll</HintPath>
	 </Reference>
	 
	 <Reference Include="BepInEx">
	   <HintPath>..\..\..\..\..\Steam\steamapps\common\Baldi's Basics Plus\BepInEx\core\BepInEx.dll</HintPath>
	 </Reference>
	 
	 <Reference Include="BepInEx.Harmony">
	   <HintPath>..\..\..\..\..\Steam\steamapps\common\Baldi's Basics Plus\BepInEx\core\BepInEx.Harmony.dll</HintPath>
	 </Reference>
	 
	 <Reference Include="PlusLevelFormat">
	   <HintPath>References\PlusLevelFormat.dll</HintPath>
	 </Reference>
	 
	 <Reference Include="PlusLevelLoader">
	   <HintPath>References\PlusLevelLoader.dll</HintPath>
	 </Reference>
	 
	 <Reference Include="PlusLevelStudio">
	   <HintPath>..\..\..\..\..\Steam\steamapps\common\Baldi's Basics Plus\BepInEx\editor before oct 8\PlusLevelStudio.dll</HintPath>
	 </Reference>
	 
	 <Reference Include="PlusStudioLevelFormat">
	   <HintPath>..\..\..\..\..\Steam\steamapps\common\Baldi's Basics Plus\BepInEx\editor before oct 8\PlusStudioLevelFormat.dll</HintPath>
	 </Reference>
	 
	 <Reference Include="PlusStudioLevelLoader">
	   <HintPath>..\..\..\..\..\Steam\steamapps\common\Baldi's Basics Plus\BepInEx\editor before oct 8\PlusStudioLevelLoader.dll</HintPath>
	 </Reference>
	 
	 <Reference Include="UnityEngine.CoreModule">
	   <HintPath>..\..\..\..\..\Steam\steamapps\common\Baldi's Basics Plus\BALDI_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
	 </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="cbldtobld.ico">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="cbldtobld.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
  </ItemGroup>

</Project>
